apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: hello
data:
  APP_MESSAGE: "Hello from ConfigMap"
  APP_ENV: "dev-local"

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
  namespace: hello
type: Opaque
stringData:
  SECRET_TOKEN: "s3cr3t-token"
